### ISSUE TITLE
Feature request: Make Copy Yaml text into Lorry feature more prominent

### ISSUE THREAD

**Issue by vegasbrianc** [CenturyLinkLabs/lorry-ui#156]
It would be great if the possibility to copy yaml text directly into an editor inside of Lorry. Many times I find a Yaml inside a blog post for example that I want to verify quickly. I then need to copy the yaml text into my text editor, save the file, then upload the Yaml to Lorry.

Being able to copy directly into Lorry would save a couple steps.

**Comment by vegasbrianc** [comment]
just found the link to copy & past yaml file. Maybe it would be good to make it a little more prominent?

**Comment by patocox** [comment]
@vegasbrianc Thanks for the feedback! We will definitely look into making this feature more prominent. It would be a shame for folks to miss out using it. It's something we leverage a lot.

**Comment by rupakg** [comment]
Implemented in release [v1.0.3](https://github.com/CenturyLinkLabs/lorry-ui/releases/tag/v1.0.3)
