### ISSUE TITLE
Command key should accept arrays

### ISSUE THREAD

**Issue by patocox** [CenturyLinkLabs/lorry-ui#158]
@BOK discovered that the `command` key only supports strings. The key should also accept arrays as this is legit docker-compose.yml. Thanks for the heads-up!

**Comment by rupakg** [comment]
Implemented in release [v1.0.3](https://github.com/CenturyLinkLabs/lorry-ui/releases/tag/v1.0.3)

/cc @BOK

**Comment by bok** [comment]
I think you are mistaken, I have never used this software...

**Comment by patocox** [comment]
sorry @bok . Should be for @hbokh
