### ISSUE TITLE
Integrate with kitematic

### ISSUE THREAD

**Issue by offlinehacker** [CenturyLinkLabs/lorry-ui#163]
I know this is not directly related with lorry, but let's just say there's huge demand to have docker-compose editor in kitematic, and you have nice editor already :) It would be really awesome if you could integrate lorry into kitematic https://github.com/kitematic/kitematic/issues/137

**Comment by davidgardner11** [comment]
I'll leave it up to the Kitematic team. They are welcome to use the Lorry editor code so long as their usage adheres to the open source license.
