### ISSUE TITLE
Support behind-the firewall, Private Registry and GitHub Enterprise

### ISSUE THREAD

**Issue by marcellodesales** [CenturyLinkLabs/lorry-ui#165]
Hi there,

Is this able to be deployed locally? I see the installation instructions requiring all the binaries of Node, Grunt, etc which differs from the current Dockerfile with only nginx... Would I be able to deploy this server locally pointing to our own Docker Registry and GitHub Enterprise? Would that also work to go to the public GitHub Enterprise?

thanks
Marcello

**Comment by davidgardner11** [comment]
Hi @marcellodesales , yes, fork the repos (lorry and lorry-ui) and modify the code to enable a connection to a private Docker Registry and GitHub Enterprise account. Unfortunately I can't give you further direction than that.
