### ISSUE TITLE
Every action on the main external page lorry.io gets timeout 

### ISSUE THREAD

**Issue by randavidovitz** [CenturyLinkLabs/lorry-ui#176]
I have tried to check the solution on your main site at lorry.io, and I get timeout on any action I try (search for images, use pre-defined templates, etc)

The issue seem to be timeout on your :9292 endpoint, for example:
1. https://lorry.io:9292/keys 
2. https://lorry.io:9292/validation

**Comment by davidgardner11** [comment]
@randavidovitz are you still experiencing this issue? Perhaps the Docker Hub was temporarily unavailable? I'm not able to reproduce this issue - search and loading a pre-defined template both worked for me. Please re-open if you are still experiencing.
